name: Maven verify

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up GPG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          # Create the .gnupg directory
          mkdir -p ~/.gnupg/
          chmod 700 ~/.gnupg

          # Import the GPG private key
          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import

          # Configure GPG to use the passphrase non-interactively
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "$GPG_PASSPHRASE" | gpg --batch --pinentry-mode loopback --passphrase-fd 0 --import ~/.gnupg/private.key

          # Reload the GPG agent
          gpg-connect-agent reloadagent /bye
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify